### PR TITLE
Update to work with latest Sphinx and IPython

### LINKED ISSUE #16: sphinx 1.8 fails when srcdir and output dir are the same
sphinxify instantiates Sphinx with the same input and output dir, but Sphinx 1.8.1 fails if this is the case:

```python
import docrepr
docrepr.sphinxify.sphinxify("", ".")
```

```
---------------------------------------------------------------------------
ApplicationError                          Traceback (most recent call last)
<ipython-input-10-6651f661623b> in <module>
      1 import docrepr
----> 2 docrepr.sphinxify.sphinxify("", ".")

~/conda/envs/torch/lib/python3.6/site-packages/docrepr/sphinxify.py in sphinxify(docstring, srcdir, output_format, temp_confdir)
    298     sphinx_app = Sphinx(srcdir, confdir, srcdir, doctreedir, output_format,
    299                         confoverrides, status=None, warning=None,
--> 300                         freshenv=True, warningiserror=False, tags=None)
    301 
    302     # Run the app

~/conda/envs/torch/lib/python3.6/site-packages/sphinx/application.py in __init__(self, srcdir, confdir, outdir, doctreedir, buildername, confoverrides, status, warning, freshenv, warningiserror, tags, verbosity, parallel, keep_going)
    158 
    159         if self.srcdir == self.outdir:
--> 160             raise ApplicationError(__('Source directory and destination '
    161                                       'directory cannot be identical'))
    162 

ApplicationError: Source directory and destination directory cannot be identical
```

I suppose a separate temporary directory needs to be created.

### LINKED ISSUE #19: Is this package abandoned?
Any chance this package will be updated any time soon? We want to use it as a dependency in our package, but it seems to need a bit of updating, couldn't get it to work.

### PR DESCRIPTION
**Pull request by fasiha**
Per @ccordoba12's comment in #19, here's a PR that updates this package to work with current Sphinx and IPython.

There were three changes required:
1. Sphinx no longer allows input and output directories to be the same. We create a temp directory to use as the output.
2. `oinspect` in IPython no longer has `argspec`, so we check for its existence.
3. The jinja2 template needs to check whether there's an actual `warning_message` before rendering it, not just the existence of a `warning` key.

To test, first set up a new conda env:
```console
conda create -n sphinx-docrepr-stuff-issue
conda activate sphinx-docrepr-stuff-issue
conda install -c conda-forge sphinx numpy ipython
```

Then, run the following in this branch:
```py
import docrepr                                # Set module options
from docrepr import sphinxify                 # html generator
from IPython.core.oinspect import Inspector   # oinfo generator

import numpy as np

oinfo = Inspector().info(np.sin)
oinfo['name'] = 'sin'
url = sphinxify.rich_repr(oinfo)
print('file://' + url)
```

> Of course, you can also check out this branch and run `python -m pip install .` to install this branch of docrepr, then run the above snippet from any directory.

This produces the following:

Screen Shot 2021-11-16 at 9 53 15 AM

With this installed, we can also confirm Jupyter and JupyterLab formats `?` docstrings out of the box! Launch `jupyter lab`, create a cell with
```py
ip = get_ipython()
ip.sphinxify_docstring = True
ip.enable_html_pager = True

import numpy
```
evaluate this, and in another cell, enter and run
```
numpy.sin?
```

docrepr-notebook

This leverages functionality added by @SylvainCorlay (see [provisional changes](https://github.com/ipython/ipython/blob/master/docs/source/whatsnew/version5.rst#provisional-changes)) in IPython (and thus ipykernel) to take advantage of docrepr if (1) it's installed and (2) if `sphinxify_docstring` is true, as we set above.

> **Nota bene** Docrepr isn't used in the JupyterLab *contextual help* yet. That requires this one-line PR in IPython: https://github.com/ipython/ipython/pull/13290 😄 if that lands, then docrepr can format documentation *everywhere* in JupyterLab! Keeping my fingers crossed.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Many thanks @fasiha for reviving this!

**Review by SylvainCorlay — APPROVED** [review]

**Comment by SylvainCorlay** [comment]
All the proposed changes look OK to me.
However I don't have commit rights anymore to the repository.

**Comment by CAM-Gerlach** [comment]
@SylvainCorlay Does the temporary destination directory need to stick around, or should it be cleaned up when execution is complete and the output file is read? If it isn't, it will accumulate space indefinitely on the user's machine. Its not used outside the scope of this function, as far as I can tell, but I'm not sure if there's another reason for leaving it there that you might be familiar with.

If so, we can replace the legacy `mkdtemp` with the modern, recommended `TemporaryDirectory`, which can be moved to this to just above line 297 where it is needed, and making it a context manager (`with tempfile.TemporaryDirectory() as destdir:` until after line 314, when the file is read. We should also make sure the open file handle gets released so the cleanup doesn't fail (particularly on Windows), so we'd also want to replace the `codecs.open(...)` with on that line the builtin `open(...)`, used as a context manager.

**Comment by fasiha** [comment]
@CAM-Gerlach *thank you so much* for these helpful comments 🙇🙏!!! You're absolutely right, the `destdir` isn't needed outside of that narrow block.

Following your cogent suggestions, https://github.com/spyder-ide/docrepr/pull/21/commits/c9a133c9ab45457fa7c225db1a2f4e635dafb0b5 will

- use TemporaryDirectory, and
- use `open` instead of `codecs.open`, and will use them as context managers.

Reinstalled and confirmed to work:

docrepr-notebook-round-2

**Comment by CAM-Gerlach** [comment]
Fantastic @fasiha , thanks so much! Merging this will also close PR #18 , since its a superset of the changes there, though unfortunately it seems GitHub will (no longer) let me link PRs to other PRs.

**Review by CAM-Gerlach — APPROVED** [review]
LGTM, unless @SylvainCorlay has any further suggestions?

**Comment by SylvainCorlay** [comment]
Thanks @CAM-Gerlach for the review and catching the temporary directory thing. This looks good to me!

**Review by SylvainCorlay — APPROVED** [review]

**Comment by CAM-Gerlach** [comment]
Thanks @fasiha for your great work, and @SylvainCorlay for the review!

**Comment by CAM-Gerlach** [comment]
Sorry for the churn, just fixing the milestones. @fasiha , if there's anything else you'd like to contribute, we'd love to have you on board! In particular, some basic tests (even smoke tests) running on the CIs would be a huge help, if that's something you might want to look in to.

**Comment by SylvainCorlay** [comment]
@CAM-Gerlach thank you for merging.
The main motivation for this at the moment is the Jupyter integration linked in the PR description.
Since this PR already makes the package functional, it would be great if there was a release tagged. We will definitely be iterating from there.

**Comment by CAM-Gerlach** [comment]
Great, @SylvainCorlay ! I added you to the repo team so you have commit rights again, and I've asked @ccordoba12 about making a release. I can also do some quick packaging/etc updates, and add some basic CI infra. It would be really great to have the CI tests working before we cut a release; right now they are in a `fabfile.py` at the root of the repo even though they don't, as far as I can tell, use Fabric at all. @ccordoba12 any insight on that? Maybe if one of you wanted to help move them to Pytest in a separate test directory, I could at least get them running on the CIs. There's also a bunch of ancient Python 2 compat code that we can clean out, and probably some depr warnings, but that can be dealt with after we get an initial release out the door, if its blocking other projects.

**Comment by SylvainCorlay** [comment]
Thanks @CAM-Gerlach for adding me. It seems that I am still a maintainer on PyPI. We should indeed fix CI before we go ahead with a release. We will look into that shortly.

**Comment by CAM-Gerlach** [comment]
Ah, that's great. If you wanted to work on the tests themselves, that would be ideal since you're much more familiar with the codebase and functionality, and once you do I can pretty easily drop in the actual GH actions workflow as I have elsewhere, since we have standardized templates for that. In the meantime, I can update the out of date packaging, release guide and such, as is also within my area of expertise and as I've been responsible for elsewhere. I'll open issues for each of these tasks.

**Pull request merged**
