### PR TITLE
Update plot directive implementation for latest sphinx

### PR DESCRIPTION
**Pull request by martinRenou**
Fix related to #26 replaces https://github.com/spyder-ide/docrepr/pull/27

### CODE REVIEW

**Comment by martinRenou** [comment]
I'm making this a draft for now. It needs some testing.

**Comment by martinRenou** [comment]
I just realized [Matplotlib provides the exact same directive](https://github.com/matplotlib/matplotlib/blob/f6e0ee49c598f59c6e6cf4eefe473e4dc634a58a/lib/matplotlib/sphinxext/plot_directive.py) (Looking at the code, it looks a lot like a copy-paste). Matplotlib's directive is compatible with latest sphinx.

At this point I believe we could ditch docrepr's `plot_directive` and use Matplotlib's one. I will open a PR doing just that. Please tell me what you think we should do going forward.

**Comment by martinRenou** [comment]
Feel free to close this PR if you believe https://github.com/spyder-ide/docrepr/pull/30 can replace it

**Comment by CAM-Gerlach** [comment]
Makes sense to me! Sorry for all the extra work on this.

**Pull request closed without merging**
